modLoader="javafml"
loaderVersion = "[1,)"
license="${license}"
issueTrackerURL = "${issues_url}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL = "${sources_url}"
logoFile="${mod_id}_icon.png"
logoBlur=false
authors="${mod_author}"
description='''
${description}
'''
[[mixins]]
    config = "${mod_id}-neoforge-integrations.mixins.json"
[[mixins]]
    config = "${mod_id}-integrations.mixins.json"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange = "${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="caelus"
    type="required"
    versionRange="${caelus_version_range}"
    ordering="NONE"
    side="BOTH"
